# Generated by Django 2.0.3 on 2018-03-25 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('records', '0007_auto_20180122_1719'),
        ('creator', '0002_auto_20180122_0811'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_identifier', models.CharField(max_length=255, unique=True)),
                ('certificate_event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='records.Event')),
                ('certificate_holder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='records.Attendee')),
            ],
        ),
    ]
