# Generated by Django 2.0.3 on 2018-03-25 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_auto_20180122_1719'),
        ('creator', '0003_certificate'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='certificate',
            unique_together={('certificate_holder', 'certificate_event')},
        ),
    ]
