# Generated by Django 2.0.3 on 2018-03-25 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0004_auto_20180325_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certificate_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.Event'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_holder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.Attendee'),
        ),
    ]
