# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-22 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_event_event_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_url',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
