# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-22 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_auto_20180122_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
