# Generated by Django 2.0.4 on 2018-04-30 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_auto_20180122_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='division',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendee',
            name='year_of_study',
            field=models.CharField(default='blank', max_length=255),
            preserve_default=False,
        ),
    ]
