# Generated by Django 2.0.4 on 2018-04-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0012_event_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='branch',
            field=models.CharField(blank=True, choices=[('IT', 'Information Technologies'), ('CS', 'Computer Engineering'), ('MECH', 'Mechnical Engineering'), ('EXTC', 'Electronics and TeleCommunication'), ('ETRX', 'Electronics')], default='IT', max_length=255),
        ),
    ]
